# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SuperApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'ASValidator', '0.1.17'
  # Pods for SuperApp
  

end
